

services:
  app:                   
    image: todo-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_URL: ${MONGO_URL}
        REDIS_URL: ${REDIS_URL}
    ports:                
      - 3000:3000
    env_file:
      - .env